# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_threads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='points',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rank',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
