# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_threads', '0002_auto_20161116_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
